### ISSUE TITLE
Translation errors - Spanish

### ISSUE THREAD

**Issue by 23GO** [JaylyDev/terminator#30]
**Describe the bug**
When you play the terminator addon, a lot of spanish translations appear to be wrong.

**To Reproduce**
1- In the die messages, 'But it respawned' shows as 'Pero reescribieron'.
2- Instead of 'Terminador de engendro' (Spawn egg)

**Expected behavior**
1- Instead of Pero reescribieron' I would translate it to 'Pero reapareció'.
2- The spawn egg should be named 'Generador de Terminator'.

**Screenshots**
![2022-01-15 (1)](https://user-images.githubusercontent.com/97795299/149626843-7356832c-8fd8-4a88-9aac-bb23af7c599d.png)
![2022-01-15](https://user-images.githubusercontent.com/97795299/149626849-c02ebb78-ed78-44bb-ba7e-cca46770a546.png)

**Addon Metadata (please complete the following information):**
 - Version: 1.3.40

**Platform (please complete the following information):**
 - Device: Windows 10
 - Website: MCPEDL
 - Minecraft Version: 1.18.2

**Additional context**
Thats all. Ill try to search for other errors. Thanks!

**Comment by JaylyDev** [comment]
noted, I’ll keep u updated

**Comment by bigguy69420** [comment]
#33 is fixed.

**Comment by 23GO** [comment]
Thanks a lot.
