### ISSUE TITLE
Use subpack to change gametest version

### ISSUE THREAD

**Issue by bigguy69420** [JaylyDev/terminator#32]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is.

ur gametest has a lot of stuff Minecraft decides this addon is platform based only

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Create subpacks for gametest stuff, downloading different versions of the addon is pain in beta

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

remove compatibility

**Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by JaylyDev** [comment]
I currently do not have time rn, pls help me develop the feature thx

**Comment by JaylyDev** [comment]
done
