### ISSUE TITLE
missing texture

### ISSUE THREAD

**Issue by ItzMeLeo9827** [JaylyDev/terminator#36]
**Describe the bug**
When Spawning the terminator, it is invisible and if there is a custom cape, it is black and pink and the terminator is invisible. and the #summon custom command also makes it invisible, shield in wrong place( creeper shield is not with the bug its my texture pack(texture pack working fine.))

**How To Reproduce**
1.
2.

**Expected behavior**
no glitched capes, invisible terminator and broken shield

**Screenshots**
on other Issue, deleted(bc I wanted to save storage) link to the pictures:https://github.com/JaylyDev/terminator/issues/35

**Addon Metadata (please complete the following information):**
Affected Version(s): [Example: v1.0.0]
All versions?
**Platform (please complete the following information):**
Affected Platform: [Example: iPhone]
Affected Minecraft Version(s): [Example: v1.16.220]
Windows 10
All versions?

**Additional context**

**Comment by JaylyDev** [comment]
please complete **How to reproduce** section.

if possible, enable content log to see if there are error logs related to the bug, thanks.

**Comment by bigguy69420** [comment]
![](https://wiki.bedrock.dev/assets/images/guide/content_log.png)

**Comment by ItzMeLeo9827** [comment]
oh thanks

**Comment by JaylyDev** [comment]
```
[Molang][error]-entity:terminator | entity:terminator | controller.render.terminator | Geometries | friendly name 'geometry.terminator' not found in entity friendly name list (geometry.default:geometry.cape) - check your spelling?

[Molang][error]-entity:terminator | entity:terminator | controller.render.terminator | Geometries | friendly name 'geometry.terminatorslim' not found in entity friendly name list (geometry.default:geometry.cape) - check your spelling?

[Molang][error]-entity:terminator | MolangScriptArg::get<>() called on incompatible type 

[Molang][error]-entity:terminator | Error processing expression ((query.variant == 0) || (query.variant == 2) || (query.variant == 4)) ? array.geos[0] : array.geos[1]

```
issue found in beta 1.3.51.8
![image](https://user-images.githubusercontent.com/65847850/151590668-f7e654d9-6e1e-48ea-b2e1-fc2fdc3a9afc.png)

please mention all the versions that has this bug thanks

**Comment by ItzMeLeo9827** [comment]
Yay thanks for the fix
