### ISSUE TITLE
Add breedable in nbt data category

### ISSUE THREAD

**Issue by bigguy69420** [JaylyDev/terminator#37]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
some people including me have been begging for breeding in minecraft

**Describe the solution you'd like**

```json
"minecraft:breedable": {
          "allow_sitting": false,
          "require_tame": false,
          "inherit_tamed": false,
          "breeds_with": [
            {
              "mate_type": "entity:terminator",
              "baby_type": "entity:terminator",
              "breed_event": {
                "event": "terminator:disable_respawn",
                "target": "baby"
              }
            },
            {
              "mate_type": "minecraft:player",
              "baby_type": "minecraft:player"
            }
          ],
          "breed_items": [
            "golden_carrot",
            "carrot"
          ]
        }
```

Add this breedable code
Set breedable to false by default (turn on by #summon command)

**Describe alternatives you've considered**
tameable or something like in #34 

**Additional context**
this is @skybird23333 alt

**Comment by bigguy69420** [comment]
Pull merge pull request #38

**Comment by skybird23333** [comment]
This is not my alt, its sussy imposter
