### ISSUE TITLE
The terminator does not respawn.

### ISSUE THREAD

**Issue by SeptemberSighter** [JaylyDev/terminator#41]
**Describe the bug**
Everytime I kill the bot it doesn't respawn. I tried every way of spawning it and it still dies without respawning

**How To Reproduce (please complete the following information):**
Steps to reproduce the bug:
1.load into a world with the bot
2.spawn and kill the bot

**Expected behavior**
As it said on DL I should be able to kill it and have it respawn 

**Content log**

**Screenshots**

**Addon Metadata (please complete the following information):**
Please list version(s) of the add-on that has this bug.
1.3.40
Affected Version(s):

**Platform (please complete the following information):**
I used this on my phone and joined on my PS4 (1.18.12)

**Comment by JaylyDev** [comment]
1. version 1.4 does not exist

2. Have you enabled the experimentals?

**Comment by SeptemberSighter** [comment]
1. I meant 1.3.40
2. I enabled experiments

**Comment by JaylyDev** [comment]
v1.3.40 is a broken version, please download the latest version (v1.3.45)
