### ISSUE TITLE
Behavior pack not importing

### ISSUE THREAD

**Issue by Respoling** [JaylyDev/terminator#45]
Interesting mod, but the behavior pack doesn't work, it comes up with 
Provided '/modules/1/type' element has an invalid value in pack manifest.
And
Multiple conflicting modules detected in pack manifest.

I'm not sure if it's just me but it needs to be fixed. 
Device on: Acer tablet with android 11 installed.

**Comment by Respoling** [comment]
If you could reply asap, ill appreciate it. Cheers.

**Comment by Respoling** [comment]
Also forgot; I used the mcpedl link, which is slow.

**Comment by JaylyDev** [comment]
Which minecraft version are you on?

**Comment by Respoling** [comment]
I went into app info and it said it was version 1.19.20.23. what now?

**Comment by JaylyDev** [comment]
What about the pack version?

**Comment by Respoling** [comment]
It's the customization update or 1.1.2, is there a problem with that?

**Comment by JaylyDev** [comment]
The latest version is [**v1.3.70**](https://github.com/JaylyDev/terminator/releases/tag/v1.3.70)

**Comment by Respoling** [comment]
Huh, maybe it's because the mcpedl link which takes a while isn't at 1.3.7. or it's something else, I'll try the MediaFire link, and let you know after.

**Comment by JaylyDev** [comment]
The mediafire link?? The only official one is the ones in this GitHub repository.

**Comment by Respoling** [comment]
Huh, the linkvertise one lead me to a mediefire, but now that I tried it again, it lead me to the GitHub, I probably clicked on a fan made scam one. I'll try again tomorrow.

**Comment by Respoling** [comment]
Good news, I tried the download and it worked, thanks for your help, and I hope we can talk again if there's a issue, thanks Jay!
